### ISSUE TITLE
 "ErrorMessage": "VSwitch 'vsw-j6ch6iui7d25x1hvw4x0r' is in unsupported zone 'cn-hongkong-b' 

### ISSUE THREAD

**Issue by yagosys** [fortinet/alicloud-aa-egress-route-failover#12]
I am trying to deploy Fortigate AA in regon hongkong. It end with up an error messages

p.s in the vars.tf file . I modified instance_ami to the corresponding region.

variable "instance_ami" {
  type    = string
  #default = "m-0xif6xxwhjlqhoaqjrr6"
  default = "m-j6c1vzhmpllrt703ln0b"

  "ErrorMessage": "VSwitch 'vsw-j6ch6iui7d25x1hvw4x0r' is in unsupported zone 'cn-hongkong-b' (allowed zones: cn-hongkong-c)"

I checked cn-hongkong-b zone. It do have this switch. But not know why Errormessages say it is unsupported zone. 

shell@Alicloud:~/fortigate-ha$ aliyun vpc DescribeVSwitches | jq '.VSwitches.VSwitch[] | "\(.VSwitchId) \(.ZoneId)"' | grep vsw-j6ch6iui7d25x1hvw4x0r
"vsw-j6ch6iui7d25x1hvw4x0r cn-hongkong-b"
shell@Alicloud:~/fortigate-ha$

see full log below. 

shell@Alicloud:~/fortigate-ha$ terraform apply
random_string.psk: Refreshing state... [id=9@0[1!$h{3S2dB[u]
random_string.random_name_post: Refreshing state... [id=gui]
alicloud_ram_policy.policy_vpc: Refreshing state... [id=FortiGateAAFailover-function-vpc-policy-gui]
data.alicloud_account.current: Refreshing state...
data.alicloud_regions.current_region_ds: Refreshing state...
alicloud_vpc.vpc: Refreshing state... [id=vpc-j6c1i27qprokf9el9n24e]
alicloud_ram_role.ram_role: Refreshing state... [id=FortiGateAAFailover-FunctionCompute-Role-gui]
alicloud_log_project.aafailoverLogging: Refreshing state... [id=fortigate-aafailover-log-gui]
data.alicloud_images.ecs_image: Refreshing state...
data.alicloud_instance_types.types_ds: Refreshing state...
data.alicloud_zones.default: Refreshing state...
data.template_file.setupPrimary: Refreshing state...
data.template_file.setupSecondary: Refreshing state...
alicloud_ram_role_policy_attachment.attach_vpc: Refreshing state... [id=role:FortiGateAAFailover-function-vpc-policy-gui:Custom:FortiGateAAFailover-FunctionCompute-Role-gui]
alicloud_log_store.aafailoverLogging-Store: Refreshing state... [id=fortigate-aafailover-log-gui:aa-failoverlog-store-gui]
alicloud_route_table.custom_route_tables[0]: Refreshing state... [id=vtb-j6cdqjgud8u7i28qes48n]
alicloud_route_table.custom_route_tables[1]: Refreshing state... [id=vtb-j6ck9zivjqtg7y18v8jz2]
alicloud_security_group.SecGroup_FC: Refreshing state... [id=sg-j6ce1ke70d9i54bifnip]
alicloud_vswitch.vsw2: Refreshing state... [id=vsw-j6csgegw97i68hb2kmvi3]
alicloud_vswitch.vsw: Refreshing state... [id=vsw-j6ch6iui7d25x1hvw4x0r]
alicloud_vswitch.vsw_internal_A: Refreshing state... [id=vsw-j6ct7r8vbaorgqp43ylm2]
alicloud_vswitch.vsw_internal_B: Refreshing state... [id=vsw-j6cvh4pxiil3ui56ouirc]
alicloud_security_group.SecGroup: Refreshing state... [id=sg-j6c5ew3n85euf1pdbtoz]
alicloud_log_store_index.log_store_index: Refreshing state... [id=fortigate-aafailover-log-gui:aa-failoverlog-store-gui]
alicloud_ram_policy.policy: Refreshing state... [id=FortiGateAAFailover-Logging-Policy-gui]
alicloud_security_group_rule.allow_all_tcp_egress: Refreshing state... [id=sg-j6c5ew3n85euf1pdbtoz:egress:tcp:1/65535:intranet:0.0.0.0/0:accept:1]
alicloud_security_group_rule.allow_all_tcp_ingress: Refreshing state... [id=sg-j6c5ew3n85euf1pdbtoz:ingress:tcp:1/65535:intranet:0.0.0.0/0:accept:1]
alicloud_security_group_rule.allow_c_class_ingress: Refreshing state... [id=sg-j6ce1ke70d9i54bifnip:ingress:tcp:1/65535:intranet:192.168.0.0/16:accept:1]
alicloud_security_group_rule.allow_a_class_ingress: Refreshing state... [id=sg-j6ce1ke70d9i54bifnip:ingress:tcp:1/65535:intranet:10.10.0.0/8:accept:1]
alicloud_security_group_rule.allow_b_class_ingress: Refreshing state... [id=sg-j6ce1ke70d9i54bifnip:ingress:tcp:1/65535:intranet:172.16.0.0/12:accept:1]
alicloud_security_group_rule.allow_all_tcp_egress_FC: Refreshing state... [id=sg-j6ce1ke70d9i54bifnip:egress:tcp:1/65535:intranet:0.0.0.0/0:accept:1]
alicloud_network_interface.PrimaryFortiGateInterface: Refreshing state... [id=eni-j6cfd1qug0hxgdtpeanc]
alicloud_network_interface.SecondaryFortigateInterface: Refreshing state... [id=eni-j6cecly8r9a9r9hrjyzf]
alicloud_route_table_attachment.custom_route_table_attachment_private[0]: Refreshing state... [id=vtb-j6cdqjgud8u7i28qes48n:vsw-j6ct7r8vbaorgqp43ylm2]
alicloud_route_table_attachment.custom_route_table_attachment_private[1]: Refreshing state... [id=vtb-j6ck9zivjqtg7y18v8jz2:vsw-j6cvh4pxiil3ui56ouirc]
alicloud_ram_role_policy_attachment.attach: Refreshing state... [id=role:FortiGateAAFailover-Logging-Policy-gui:Custom:FortiGateAAFailover-FunctionCompute-Role-gui]
alicloud_route_entry.custom_route_table_egress[0]: Refreshing state... [id=vtb-j6cdqjgud8u7i28qes48n:vrt-j6ccn8bkpx4ngo6u5i54v:0.0.0.0/0:NetworkInterface:eni-j6cfd1qug0hxgdtpeanc]
alicloud_route_entry.custom_route_table_egress[1]: Refreshing state... [id=vtb-j6ck9zivjqtg7y18v8jz2:vrt-j6ccn8bkpx4ngo6u5i54v:0.0.0.0/0:NetworkInterface:eni-j6cecly8r9a9r9hrjyzf]
alicloud_instance.SecondaryFortigate: Refreshing state... [id=i-j6ch4wa069moj2a1f3g5]
alicloud_instance.PrimaryFortigate: Refreshing state... [id=i-j6c6lt03725edmfqrp0d]
alicloud_network_interface_attachment.PrimaryFortigateattachment: Refreshing state... [id=eni-j6cfd1qug0hxgdtpeanc:i-j6c6lt03725edmfqrp0d]
alicloud_network_interface_attachment.SecondaryFortigateAttachment: Refreshing state... [id=eni-j6cecly8r9a9r9hrjyzf:i-j6ch4wa069moj2a1f3g5]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # alicloud_fc_function.fortigate-AA-Failover will be created
  + resource "alicloud_fc_function" "fortigate-AA-Failover" {
      + code_checksum         = (known after apply)
      + description           = "FortiGate aafailover - AliCloud Created by Terraform"
      + environment_variables = {
          + "ACCESS_KEY_ID"               = " "
          + "ACCESS_KEY_SECRET"           = " "
          + "ENDPOINT_ECS"                = "https://ecs.aliyuncs.com"
          + "ENDPOINT_ESS"                = "https://vpc.aliyuncs.com"
          + "PIN_TO"                      = "both"
          + "PRIMARY_FORTIGATE_ID"        = "i-j6c6lt03725edmfqrp0d"
          + "PRIMARY_FORTIGATE_SEC_ENI"   = "eni-j6cfd1qug0hxgdtpeanc"
          + "REGION"                      = "cn-hongkong"
          + "ROUTE_TABLE_ID"              = "vtb-j6cdqjgud8u7i28qes48n,vtb-j6ck9zivjqtg7y18v8jz2,vtb-j6cf3seuj6xl0g5irp1mo"
          + "SECONDARY_FORTIGATE_ID"      = "i-j6ch4wa069moj2a1f3g5"
          + "SECONDARY_FORTIGATE_SEC_ENI" = "eni-j6cecly8r9a9r9hrjyzf"
          + "managedby"                   = "Created with Terraform"
        }
      + filename              = "./dist/failoverAAindex.zip"
      + function_id           = (known after apply)
      + handler               = "index.main"
      + id                    = (known after apply)
      + last_modified         = (known after apply)
      + memory_size           = 512
      + name                  = "Fortigate-AA-Failover-gui"
      + runtime               = "nodejs8"
      + service               = "FortiGateAAFailover-gui"
      + timeout               = 500
    }

  # alicloud_fc_function.fortigate-callHealthCheck will be created
  + resource "alicloud_fc_function" "fortigate-callHealthCheck" {
      + code_checksum         = (known after apply)
      + description           = "FortiGate AA-Failover - AliCloud Created by Terraform"
      + environment_variables = {
          + "API_KEY"   = " "
          + "FULL_URL"  = "https://5498321147060270.cn-hongkong-internal.fc.aliyuncs.com/2016-08-15/proxy/FortiGateAAFailover-gui/Fortigate-AA-Failover-gui/"
          + "managedby" = "Created with Terraform"
        }
      + filename              = "./dist/callHealthCheck.zip"
      + function_id           = (known after apply)
      + handler               = "callHealthCheck.callHealthCheck"
      + id                    = (known after apply)
      + last_modified         = (known after apply)
      + memory_size           = 512
      + name                  = "Fortigate-callHealthCheck-gui"
      + runtime               = "nodejs8"
      + service               = "FortiGateAAFailover-gui"
      + timeout               = 500
    }

  # alicloud_fc_service.fortigate-failover-service will be created
  + resource "alicloud_fc_service" "fortigate-failover-service" {
      + description     = "Created by terraform"
      + id              = (known after apply)
      + internet_access = true
      + last_modified   = (known after apply)
      + name            = "FortiGateAAFailover-gui"
      + role            = "acs:ram::5498321147060270:role/fortigateaafailover-functioncompute-role-gui"
      + service_id      = (known after apply)

      + log_config {
          + logstore = "aa-failoverlog-store-gui"
          + project  = "fortigate-aafailover-log-gui"
        }

      + vpc_config {
          + security_group_id = "sg-j6ce1ke70d9i54bifnip"
          + vpc_id            = (known after apply)
          + vswitch_ids       = [
              + "vsw-j6ch6iui7d25x1hvw4x0r",
            ]
        }
    }

  # alicloud_fc_trigger.httptrigger will be created
  + resource "alicloud_fc_trigger" "httptrigger" {
      + config        = jsonencode(
            {
              + authType          = "anonymous"
              + enable            = true
              + functionParameter = {
                  + a = "b"
                  + c = "d"
                }
              + jobConfig         = {
                  + maxRetryTime    = 3
                  + triggerInterval = 200
                }
              + logConfig         = {
                  + logstore = "aa-failoverlog-store-gui"
                  + project  = "fortigate-aafailover-log-gui"
                }
              + methods           = [
                  + "GET",
                  + "POST",
                ]
              + sourceConfig      = {
                  + logstore = "project-for-fc"
                  + project  = "project-for-fc"
                }
            }
        )
      + function      = "Fortigate-AA-Failover-gui"
      + id            = (known after apply)
      + last_modified = (known after apply)
      + name          = "HTTPTrigger"
      + service       = "FortiGateAAFailover-gui"
      + trigger_id    = (known after apply)
      + type          = "http"
    }

  # alicloud_fc_trigger.timer will be created
  + resource "alicloud_fc_trigger" "timer" {
      + config        = jsonencode(
            {
              + authType          = "anonymous"
              + cronExpression    = "@every 1m"
              + enable            = true
              + functionParameter = {
                  + a = "b"
                  + c = "d"
                }
              + jobConfig         = {
                  + maxRetryTime    = 3
                  + triggerInterval = 60
                }
              + logConfig         = {
                  + logstore = "aa-failoverlog-store-gui"
                  + project  = "fortigate-aafailover-log-gui"
                }
              + methods           = [
                  + "GET",
                  + "POST",
                ]
              + sourceConfig      = {
                  + logstore = "project-for-fc"
                  + project  = "project-for-fc"
                }
            }
        )
      + function      = "Fortigate-callHealthCheck-gui"
      + id            = (known after apply)
      + last_modified = (known after apply)
      + name          = "CronTrigger"
      + service       = "FortiGateAAFailover-gui"
      + trigger_id    = (known after apply)
      + type          = "timer"
    }

Plan: 5 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

alicloud_fc_service.fortigate-failover-service: Creating...

Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_fc_service.go:157: Resource alicloud_fc_service CreateService Failed!!! [SDK fc-go-sdk ERROR]:
{
  "HttpStatus": 400,
  "RequestId": "e8aa362d-57e4-4e54-9738-ed588e8a321b",
  "ErrorCode": "InvalidArgument",
  "ErrorMessage": "VSwitch 'vsw-j6ch6iui7d25x1hvw4x0r' is in unsupported zone 'cn-hongkong-b' (allowed zones: cn-hongkong-c)"
}

  on main.tf line 283, in resource "alicloud_fc_service" "fortigate-failover-service":
283: resource "alicloud_fc_service" "fortigate-failover-service" {

shell@Alicloud:~/fortigate-ha$ aliyun vpc DescribeVSwitches | jq '.VSwitches.VSwitch[] | "\(.VSwitchId) \(.ZoneId)"' | grep vsw-j6ch6iui7d25x1hvw4x0r
"vsw-j6ch6iui7d25x1hvw4x0r cn-hongkong-b"
shell@Alicloud:~/fortigate-ha$

**Comment by Joel-Cripps** [comment]
Hey Yagosys,
That looks like an error with the vswitch we attach to the function. If you look on line 283 in the main.tf under  `resource "alicloud_fc_service" "fortigate-failover-service" ` You will see 
```
  vpc_config {
    vswitch_ids = [var.region == "ap-southeast-5" ? alicloud_vswitch.vsw2.id : alicloud_vswitch.vsw.id]
    security_group_id = alicloud_security_group.SecGroup_FC.id
  }
```
I believe you will need to change the vswitch  on line 278 to:  `vswitch_ids = alicloud_vswitch.vsw2.id`

It looks like the hongkong region has zones b/c and no a.  Some regions only support attaching a vswitch to a function in one zone. 

Let me know if you continue to have issues. I'll take a look into a mapping functionality for the vswitch attachment.
