### ISSUE TITLE
prepackage fuction code for end user

### ISSUE THREAD

**Issue by cmj2010** [fortinet/alicloud-aa-egress-route-failover#15]
Customer hope if we can prepackage callHealthCheck.zip and failoverAAindex.zip, customer want to run the terraform and they need to run package.json first, but we havn't document for it now.

**Comment by Joel-Cripps** [comment]
Hey,
There is a release on github at https://github.com/fortinet/alicloud-aa-egress-route-failover/releases/tag/0.2.0 which contains the necessary files.  Or you can  clone this repo (`git clone`) and then run:

 `npm install` and `npm setup` 
 
 which will generate the two zip packages. 

The package.json is located in the repo: https://github.com/fortinet/alicloud-aa-egress-route-failover/blob/master/package.json

Let me know if you need more info.

**Comment by cmj2010** [comment]
Thanks, the release is fit customer request.
